#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'

if $0 ==__FILE__
  $LOAD_PATH.unshift File.dirname(__FILE__) + "/../../"
  module Yap
    module Shell
      module Parser
      end
    end
  end
  require 'yap/shell/parser/nodes'

end

module Yap
  module Shell
    class ParserImpl < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 101)
  include Yap::Shell::Parser::Nodes
#=end
  def parse(str)
    @yydebug = true

    @q = Yap::Shell::Parser::Lexer.new.tokenize(str)
    # @q.push [false, '$']   # is optional from Racc 1.3.7
# puts @q.inspect
# puts "---- parse tree follows ----"
    __send__(Racc_Main_Parsing_Routine, _racc_setup(), false)
    # do_parse
  end

  def next_token
    @q.shift
  end

...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    18,    19,    28,    22,    20,    34,    18,    19,    28,    16,
    20,    11,    41,     6,    28,    16,    22,    11,    37,     6,
    18,    19,    11,    43,    20,    24,    18,    19,    23,    16,
    20,    11,    22,     6,    42,    16,    21,    11,    30,     6,
    18,    19,    44,    31,    20,    42,    18,    19,    42,    16,
    20,    11,    23,     6,    24,    16,    11,    11,   nil,     6,
    18,    19,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    33 ]

racc_action_check = [
     0,     0,    19,    26,     0,    16,    11,    11,    18,     0,
    11,     0,    26,     0,    10,    11,    29,    11,    21,    11,
     6,     6,     5,    29,     6,     4,    24,    24,     3,     6,
    24,     6,     2,     6,    27,    24,     1,    24,    12,    24,
    23,    23,    33,    12,    23,    35,    22,    22,    36,    23,
    22,    23,    38,    23,    39,    22,    40,    22,   nil,    22,
    15,    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15 ]

racc_action_pointer = [
    -2,    36,    25,    20,    16,     9,    18,   nil,   nil,   nil,
    10,     4,    33,   nil,   nil,    58,    -7,   nil,     4,    -2,
   nil,    18,    44,    38,    24,   nil,    -4,    30,   nil,     9,
   nil,   nil,   nil,    30,   nil,    41,    44,   nil,    44,    45,
    43,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -33,   -33,    -1,    -3,    -5,    -7,   -33,   -10,   -11,   -12,
   -14,   -33,   -17,   -19,   -20,   -21,   -33,   -25,   -26,   -28,
   -32,   -33,   -33,   -33,   -33,    -9,   -33,   -13,   -30,   -33,
   -16,   -18,   -22,   -33,   -24,   -27,   -29,    45,    -2,    -4,
    -6,    -8,   -31,   -15,   -23 ]

racc_goto_table = [
    25,     2,    27,    40,    39,    38,     1,    26,    32,   nil,
    35,    36,    29,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    25 ]

racc_goto_check = [
     6,     2,    10,     5,     4,     3,     1,     2,    13,   nil,
    10,    10,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6 ]

racc_goto_pointer = [
   nil,     6,     1,   -17,   -19,   -21,    -5,   nil,   nil,   nil,
    -8,   nil,   nil,    -7,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     7,     8,     9,    10,
   nil,    12,    13,    14,    15,    17 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 18, :_reduce_none,
  3, 19, :_reduce_2,
  1, 19, :_reduce_3,
  3, 20, :_reduce_4,
  1, 20, :_reduce_none,
  3, 21, :_reduce_6,
  1, 21, :_reduce_none,
  3, 22, :_reduce_8,
  2, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  2, 23, :_reduce_none,
  1, 23, :_reduce_none,
  3, 26, :_reduce_none,
  2, 24, :_reduce_16,
  1, 24, :_reduce_none,
  2, 28, :_reduce_18,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  2, 29, :_reduce_22,
  3, 31, :_reduce_23,
  2, 31, :_reduce_24,
  1, 30, :_reduce_none,
  1, 32, :_reduce_26,
  2, 32, :_reduce_27,
  1, 32, :_reduce_28,
  2, 32, :_reduce_29,
  1, 27, :_reduce_30,
  2, 27, :_reduce_31,
  1, 25, :_reduce_32 ]

racc_reduce_n = 33

racc_shift_n = 45

racc_token_table = {
  false => 0,
  :error => 1,
  :Command => 2,
  :LiteralCommand => 3,
  :Argument => 4,
  :Heredoc => 5,
  :InternalEval => 6,
  :Separator => 7,
  :Conditional => 8,
  :Pipe => 9,
  :Redirection => 10,
  :LValue => 11,
  :RValue => 12,
  :BeginCommandSubstitution => 13,
  :EndCommandSubstitution => 14,
  "(" => 15,
  ")" => 16 }

racc_nt_base = 17

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "Command",
  "LiteralCommand",
  "Argument",
  "Heredoc",
  "InternalEval",
  "Separator",
  "Conditional",
  "Pipe",
  "Redirection",
  "LValue",
  "RValue",
  "BeginCommandSubstitution",
  "EndCommandSubstitution",
  "\"(\"",
  "\")\"",
  "$start",
  "program",
  "stmts",
  "stmt",
  "pipeline",
  "stmts2",
  "stmt_w_substitutions",
  "command_w_heredoc",
  "internal_eval",
  "stmt_w_substitutions2",
  "args",
  "command_w_redirects",
  "command_w_vars",
  "command",
  "vars",
  "command2" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'grammar.y', 23)
  def _reduce_2(val, _values, result)
     result = StatementsNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 25)
  def _reduce_3(val, _values, result)
     result = StatementsNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_4(val, _values, result)
     result = ConditionalNode.new(val[1].value, val[0], val[2]) 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'grammar.y', 32)
  def _reduce_6(val, _values, result)
     result = PipelineNode.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'grammar.y', 36)
  def _reduce_8(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'grammar.y', 48)
  def _reduce_16(val, _values, result)
     val[0].heredoc = val[1] ; result = val[0] 
    result
  end
.,.,

# reduce 17 omitted

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_18(val, _values, result)
     val[0].redirects << RedirectionNode.new(val[1].value, val[1].attrs[:target]) ; result = val[0] 
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'grammar.y', 58)
  def _reduce_22(val, _values, result)
     result = EnvWrapperNode.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 61)
  def _reduce_23(val, _values, result)
     val[0].add_var(val[1].value, val[2].value) ; result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 63)
  def _reduce_24(val, _values, result)
     result = EnvNode.new(val[0].value, val[1].value) 
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'grammar.y', 68)
  def _reduce_26(val, _values, result)
     result = CommandNode.new(val[0].value) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 70)
  def _reduce_27(val, _values, result)
     result = CommandNode.new(val[0].value, val[1].flatten) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 72)
  def _reduce_28(val, _values, result)
     result = CommandNode.new(val[0].value, literal:true) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 74)
  def _reduce_29(val, _values, result)
     result = CommandNode.new(val[0].value, val[1].flatten, literal:true) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 77)
  def _reduce_30(val, _values, result)
     result = [val[0].value] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 79)
  def _reduce_31(val, _values, result)
     result = [val[0], val[1].value] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_32(val, _values, result)
     result = InternalEvalNode.new(val[0].value) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class ParserImpl
    end   # module Shell
  end   # module Yap


if $0 == __FILE__
  $LOAD_PATH.unshift File.dirname(__FILE__) + "/lib/"
  require 'yap/shell/parser/lexer'
  require 'yap/shell/parser/nodes'
    [
    "(foo a b && (bar c d | baz e f))"
    ].each do |src|
      puts 'parsing:'
      print src
      puts
      puts 'result:'
      require 'pp'
      ast = Yap::Shell::ParserImpl.new.parse(src)
      pp ast
    end


  # puts "---- Evaluating"
  #   require 'pry'
  # binding.pry
  # Evaluator.new.evaltree(ast)
end
